-- Database Create
CREATE DATABASE user_management;

-- Oluşturulmuş database seçmek
USE user_management;

-- user adında bir tablo oluştur
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

-- ###################################################################################################################

-- Insert
MERGE INTO users (id, username, password, email) KEY(id) VALUES (1,'birsel','123456','binokta@hotmail.com' )

-- Select
select * FROM users;

-- Find User
SELECT  *  FROM users WHERE username="birsel" AND "123456";

-- Update
UPDATE users SET username="birsel4423", password="123456", email="binokta@hotmail.com" WHERE id=1;

-- delete
DELETE FROM users  WHERE id=1;
